import { useState, useEffect, useCallback } from 'react';
import { User, Building2, Briefcase, RefreshCw } from 'lucide-react';
import { Card } from '../../Card';
import { WizardData } from '../types';
import { PersonaFisicaForm } from './forms/PersonaFisicaForm';
import { ImpresaForm } from './forms/ImpresaForm';
import { ProfessionistaForm } from './forms/ProfessionistaForm';
import { loadImpostazioni, generateCodiceCliente, type FormatoCodice } from '../../../lib/codiceGenerator';

interface Step1Props {
  formData: WizardData;
  updateFormData: (updates: Partial<WizardData>) => void;
  onTipoClienteChange: (tipo: 'persona_fisica' | 'impresa' | 'professionista') => void;
  isEditMode?: boolean;
  clienteId?: string;
}

export function Step1DatiCliente({ formData, updateFormData, onTipoClienteChange, isEditMode, clienteId }: Step1Props) {
  const [formatoCliente, setFormatoCliente] = useState<FormatoCodice>('manuale');
  const [generatingCode, setGeneratingCode] = useState(false);

  useEffect(() => {
    loadImpostazioni().then(imp => setFormatoCliente(imp.formato_codice_cliente));
  }, []);

  const nomeCliente = formData.tipo_cliente === 'persona_fisica'
    ? formData.nome_cognome_pf
    : formData.tipo_cliente === 'professionista'
      ? formData.nome_cognome_prof
      : formData.ragione_sociale;

  const cfPivaCliente = formData.tipo_cliente === 'persona_fisica'
    ? formData.codice_fiscale_pf
    : formData.tipo_cliente === 'professionista'
      ? (formData.partita_iva_prof || formData.codice_fiscale_prof)
      : (formData.partita_iva_impresa || formData.codice_fiscale_impresa);

  // Rigenera manualmente (pulsante refresh) — sempre permesso
  const manualRegenerate = useCallback(async () => {
    if (formatoCliente === 'manuale') return;
    if (formatoCliente === 'nome' && !nomeCliente) return;
    if (formatoCliente === 'cf_piva' && !cfPivaCliente) return;
    setGeneratingCode(true);
    const codice = await generateCodiceCliente(formatoCliente, nomeCliente || '', undefined, cfPivaCliente || '');
    if (codice) updateFormData({ codice_cliente: codice });
    setGeneratingCode(false);
  }, [formatoCliente, nomeCliente, cfPivaCliente]);

  // Auto-genera solo in modalità creazione (non in modifica, per preservare eventuali modifiche manuali)
  const autoGenerate = useCallback(async () => {
    if (isEditMode) return;
    await manualRegenerate();
  }, [isEditMode, manualRegenerate]);

  // Per formato 'nome', rigenera quando cambia il nome
  useEffect(() => {
    if (formatoCliente === 'nome' && nomeCliente && nomeCliente.length >= 2) {
      autoGenerate();
    }
  }, [formatoCliente, nomeCliente]);

  // Per formato 'cf_piva', rigenera quando cambia il CF/P.IVA
  useEffect(() => {
    if (formatoCliente === 'cf_piva' && cfPivaCliente && cfPivaCliente.length >= 11) {
      autoGenerate();
    }
  }, [formatoCliente, cfPivaCliente]);

  // Per formato 'sequenziale', rigenera quando cambia nome o CF/P.IVA (inclusi nel codice)
  useEffect(() => {
    if (formatoCliente === 'sequenziale') {
      autoGenerate();
    }
  }, [formatoCliente, nomeCliente, cfPivaCliente]);

  const isAutoGenerated = formatoCliente !== 'manuale';

  return (
    <Card title="Step 1: Dati Cliente">
      <div className="space-y-6">
        {/* SELEZIONE TIPO CLIENTE */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-3">
            Tipo Cliente *
          </label>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            <button
              type="button"
              onClick={() => onTipoClienteChange('persona_fisica')}
              className={`p-4 border-2 rounded-lg flex items-center gap-3 transition-all ${
                formData.tipo_cliente === 'persona_fisica'
                  ? 'border-blue-600 bg-blue-50'
                  : 'border-gray-300 hover:border-gray-400'
              }`}
            >
              <User className={`w-6 h-6 ${formData.tipo_cliente === 'persona_fisica' ? 'text-blue-600' : 'text-gray-400'}`} />
              <div className="text-left">
                <div className="font-semibold">Persona Fisica</div>
                <div className="text-xs text-gray-500">Cliente privato</div>
              </div>
            </button>

            <button
              type="button"
              onClick={() => onTipoClienteChange('impresa')}
              className={`p-4 border-2 rounded-lg flex items-center gap-3 transition-all ${
                formData.tipo_cliente === 'impresa'
                  ? 'border-blue-600 bg-blue-50'
                  : 'border-gray-300 hover:border-gray-400'
              }`}
            >
              <Building2 className={`w-6 h-6 ${formData.tipo_cliente === 'impresa' ? 'text-blue-600' : 'text-gray-400'}`} />
              <div className="text-left">
                <div className="font-semibold">Impresa</div>
                <div className="text-xs text-gray-500">Società/Ente
</div>
              </div>
            </button>

            <button
              type="button"
              onClick={() => onTipoClienteChange('professionista')}
              className={`p-4 border-2 rounded-lg flex items-center gap-3 transition-all ${
                formData.tipo_cliente === 'professionista'
                  ? 'border-blue-600 bg-blue-50'
                  : 'border-gray-300 hover:border-gray-400'
              }`}
            >
              <Briefcase className={`w-6 h-6 ${formData.tipo_cliente === 'professionista' ? 'text-blue-600' : 'text-gray-400'}`} />
              <div className="text-left">
                <div className="font-semibold">Professionista</div>
                <div className="text-xs text-gray-500">Libero professionista</div>
              </div>
            </button>
          </div>
        </div>

        {/* CODICE CLIENTE (comune a tutti) */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Codice Cliente *
            {isAutoGenerated && (
              <span className="ml-2 text-xs text-blue-600 font-normal">
                (generazione automatica: {formatoCliente})
              </span>
            )}
          </label>
          <div className="flex gap-2">
            <input
              type="text"
              value={formData.codice_cliente}
              onChange={(e) => updateFormData({ codice_cliente: e.target.value })}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              placeholder={isAutoGenerated ? 'Generato automaticamente...' : 'es. CLI-001'}
            />
            {isAutoGenerated && (
              <button
                type="button"
                onClick={manualRegenerate}
                disabled={generatingCode || (formatoCliente === 'nome' && !nomeCliente)}
                className="px-3 py-2 bg-blue-100 text-blue-700 rounded-lg hover:bg-blue-200 disabled:opacity-50 flex-shrink-0"
                title="Rigenera codice"
              >
                <RefreshCw className="w-4 h-4" />
              </button>
            )}
          </div>
          {formatoCliente === 'nome' && !nomeCliente && (
            <p className="text-xs text-amber-600 mt-1">Inserisci il nome del cliente per generare il codice.</p>
          )}
        </div>

        {/* FORM SPECIFICI PER TIPO CLIENTE */}
        {formData.tipo_cliente === 'persona_fisica' && (
          <PersonaFisicaForm formData={formData} updateFormData={updateFormData} />
        )}

        {formData.tipo_cliente === 'impresa' && (
          <ImpresaForm formData={formData} updateFormData={updateFormData} clienteId={clienteId} />
        )}

        {formData.tipo_cliente === 'professionista' && (
          <ProfessionistaForm formData={formData} updateFormData={updateFormData} clienteId={clienteId} />
        )}
      </div>
    </Card>
  );
}
